### PR TITLE
Update to Play 2.8.0

### PR DESCRIPTION
**Pull request by wsargent**
Update everything to Silhouette 6.1.0

There's a lot of changes in here: in my defense I was playing around with Silhouette using your project as a base.

* Update to Play 2.8.0
* Update to sbt 1.3.6
* Update to Silhouette 6.1.0
* Make failure cases more explicit in AuthenticationController
* Add CSRF form fields to forms and enable the default filters (they work in 2.8.0)
* Add AbstractController to hide all the silhouette injections
* Add MyRequest to minimize need for user/messages/request to be passed
into templates.
* Use messages to capitalize placeholder / labels in message helpers.
* Use in memory H2 database using MySQL dialect for easy setup.
* Use custom error handlers to redirect back to home page on auth
failure.

### CODE REVIEW

**Comment by thomasmatecki** [comment]
@wsargent Let me know when you feel this is complete.

**Comment by wsargent** [comment]
Oh!  Yes, it’s complete.  Sorry, I forgot it was a branch!

**Comment by philliptaylorpro** [comment]
I say this to be constructive but when you aggressively refactor this code and add brand new traits like this: app/controllers/SecuredRequestHeader.scala and app/controllers/AppRequest.scala with lots of typeclasses it becomes impossible for users to understand the Silhouette API, what's provided and what isn't as what is essential. The current master doesn't touch MessagesAPI at all and yet you've wound it deeply in to code that people think they need to copy and paste in order to get the Silhouette API working.

People want something working quickly so they want the absolute minimal MVP of configuration and then they can iteratively come to the sorts of nice refactorings you've implemented independently once they understand the core types. That's made harder when more and more traits like the ones you've added are present.

My feedback as someone following the tutorials is that current master of this project is the most readable of any that silhouette provides and apart from the classTag change needing to be made to support 6.1.0 and tests in the home controller that use GuiceApplicationBuilder and simulate both Unauthorised and Success, I don't think this a good improvement personally.

I hope that you understand I've written this with the best intentions. Your solution is undeniably elegant.

**Comment by thomasmatecki** [comment]
@wsargent - apologies for the delay in looking at this. This code looks good.

I do tend to agree with @philliptaylorpro. When I first started looking at slick I was a bit overwhelmed by many of the examples. My objective for this repo was to put forth the _simplest_ thing that demonstrated the _smallest_ useful piece of the silhouette API. Adding a bunch of stuff here really defeats that purpose.

**Comment by wsargent** [comment]
Okay, I'll see what I can do to strip it down more.  Most of this is already in https://github.com/mohiva/play-silhouette-seed/pull/118 and https://github.com/mohiva/play-silhouette-seed/pull/112 anyway.

**Comment by thomasmatecki** [comment]
@wsargent very nice. I was going to propose a fork of this repo as an alternate, more in depth example.

**Comment by tunesmith** [comment]
Question about this PR: 

I understand the logic of separating `USER_PROFILE` from `USER`, as a User might have multiple profiles. I gather an example might be using an additional TOTP password to "activate" a user through email.

I also understand that in the absence of a unique `id` field in `USER_PROFILE`, the need for the joint primary key of `PROVIDER_ID` and `PROVIDER_KEY`, as `PROVIDER_KEY` is not unique by itself.

But if so, then shouldn't the password be associated with the profile, rather than the user? Since password refers only to the `PROVIDER_KEY` (which is in turn the user's email), this doesn't support each profile having a separate password. Does `PASSWORD` need `PROVIDER_ID` added to it (or otherwise refer to a new unique key in `USER_PROFILE`)? 

I'm still learning silhouette so I might be entirely wrong. And I understand this PR is a bit defunct - I'm just referring to both this seed and this PR as I try to get something up and running with Play 2.8.2 and silhouette 7.

**Pull request closed without merging**
